all: experiment client server

experiment: experiment.c
	gcc experiment.c -o experiment

client: client.c
	gcc client.c -o client

server: server.c
	gcc server.c -o server

clean:
	rm experiment client server
